//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryHelper.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GroceryHelper.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        internal static string UserTitle {
            get {
                return ResourceManager.GetString("UserTitle", resourceCulture);
            }
        }
        
        internal static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        internal static string ToBuyItemDetailTitle {
            get {
                return ResourceManager.GetString("ToBuyItemDetailTitle", resourceCulture);
            }
        }
        
        internal static string AddListTitle {
            get {
                return ResourceManager.GetString("AddListTitle", resourceCulture);
            }
        }
        
        internal static string NewItemTitle {
            get {
                return ResourceManager.GetString("NewItemTitle", resourceCulture);
            }
        }
        
        internal static string SyncTitle {
            get {
                return ResourceManager.GetString("SyncTitle", resourceCulture);
            }
        }
        
        internal static string GroceryStorePageTitle {
            get {
                return ResourceManager.GetString("GroceryStorePageTitle", resourceCulture);
            }
        }
        
        internal static string CreateGroceryListPageTitle {
            get {
                return ResourceManager.GetString("CreateGroceryListPageTitle", resourceCulture);
            }
        }
        
        internal static string EditItemTitle {
            get {
                return ResourceManager.GetString("EditItemTitle", resourceCulture);
            }
        }
        
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        internal static string AddListButton {
            get {
                return ResourceManager.GetString("AddListButton", resourceCulture);
            }
        }
        
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        internal static string IsDoneLabel {
            get {
                return ResourceManager.GetString("IsDoneLabel", resourceCulture);
            }
        }
        
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        internal static string NewItemButton {
            get {
                return ResourceManager.GetString("NewItemButton", resourceCulture);
            }
        }
        
        internal static string SyncButton {
            get {
                return ResourceManager.GetString("SyncButton", resourceCulture);
            }
        }
        
        internal static string GroceryStorePageButton {
            get {
                return ResourceManager.GetString("GroceryStorePageButton", resourceCulture);
            }
        }
        
        internal static string CreateGroceryListPageButton {
            get {
                return ResourceManager.GetString("CreateGroceryListPageButton", resourceCulture);
            }
        }
        
        internal static string CreateListButton {
            get {
                return ResourceManager.GetString("CreateListButton", resourceCulture);
            }
        }
        
        internal static string ClearListButton {
            get {
                return ResourceManager.GetString("ClearListButton", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        internal static string PleaseSelectItem {
            get {
                return ResourceManager.GetString("PleaseSelectItem", resourceCulture);
            }
        }
        
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        internal static string Aisle {
            get {
                return ResourceManager.GetString("Aisle", resourceCulture);
            }
        }
        
        internal static string ManualModeButton {
            get {
                return ResourceManager.GetString("ManualModeButton", resourceCulture);
            }
        }
        
        internal static string StoreModeButton {
            get {
                return ResourceManager.GetString("StoreModeButton", resourceCulture);
            }
        }
    }
}
